// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgKwmYEurd9AzKM_uko_FHG90gIC9GDdk',
    appId: '1:437506124492:web:368d4639e3a90ca6177069',
    messagingSenderId: '437506124492',
    projectId: 'tripgenie153',
    authDomain: 'tripgenie153.firebaseapp.com',
    storageBucket: 'tripgenie153.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44VJLsvK8cn1uZlOK1eXv6gjnOWEKb1I',
    appId: '1:437506124492:android:44f9a1f77ebb0fdf177069',
    messagingSenderId: '437506124492',
    projectId: 'tripgenie153',
    storageBucket: 'tripgenie153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbXymBrArgvMQPebs8HVff7C3oSNKL3zQ',
    appId: '1:437506124492:ios:98796076063ca75c177069',
    messagingSenderId: '437506124492',
    projectId: 'tripgenie153',
    storageBucket: 'tripgenie153.firebasestorage.app',
    androidClientId: '437506124492-vavc7lilps2n8pe56m482lo0fseahmkq.apps.googleusercontent.com',
    iosClientId: '437506124492-4uiiav3kii4cvh325l73cfi1n89kn6cd.apps.googleusercontent.com',
    iosBundleId: 'com.zenith.tripgenie',
  );

}